package MY_DSA.Leet;

public class Leet3270 {
    class Solution {
        public int generateKey(int num1, int num2, int num3) {
            int ans = 0, count = 1, i = 0;
            while (i < 4) {
                int min = Math.min(num1 % 10, Math.min(num2 % 10, num3 % 10));
                ans = ans + min * count;
                num1 /= 10;
                num2 /= 10;
                num3 /= 10;
                count *= 10;
                i++;
            }
            return ans;
        }
    }
}

/*
using strings for formating

 class Solution {
        public int generateKey(int num1, int num2, int num3) {
            int ans=0;
            String n1=String.format("%04d",num1);
            String n2=String.format("%04d",num2);
            String n3=String.format("%04d",num3);

            for(int i=0;i<4;i++){
                int curr = Math.min(n1.charAt(i)-'0' , Math.min(n2.charAt(i)-'0', n3.charAt(i)-'0'));
                ans =ans*10+curr ;
            }
            return ans;
        }
    }
*/




/*

You are given three positive integers num1, num2, and num3.

The key of num1, num2, and num3 is defined as a four-digit number such that:

Initially, if any number has less than four digits, it is padded with leading zeros.
The ith digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the ith digits of num1, num2, and num3.
Return the key of the three numbers without leading zeros (if any).



Example 1:

Input: num1 = 1, num2 = 10, num3 = 1000

Output: 0

Explanation:

        On padding, num1 becomes "0001", num2 becomes "0010", and num3 remains "1000".

The 1st digit of the key is min(0, 0, 1).
The 2nd digit of the key is min(0, 0, 0).
The 3rd digit of the key is min(0, 1, 0).
The 4th digit of the key is min(1, 0, 0).
Hence, the key is "0000", i.e. 0.
*/
